- name: Pull and run image from docker hub
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Pull docker image
      shell: docker pull shashnagaral/calculator-mini-project:latest

    - name: Get container info
      docker_container_info:
        name: calculator
      register: result

    - name: Remove container if exists
      shell: docker stop calculator && docker rm calculator
      when: result.exists

    - name: Run docker image
      shell: docker run -it --name calculator -d shashnagaral/calculator-mini-project:latest